### ISSUE TITLE
SIGSEGV on EOS 4.15.4F/4.15.3F

### ISSUE THREAD

**Issue by innoying** [aristanetworks/EosSdk#11]
I'm having an issue where running any script that utilizes `main_loop` results in a SIGSEGV on `EOS 4.15.4F` or `EOS 4.15.3F` when using `EosSdk-1.7.0-4.15.2F.i686.rpm` on a `Arista DCS-7150S-24-R`

Obviously the version numbers don't match here, however I'd like to know if this is expected behavior to have to wait for an updated EosSdk release before completing any firmware updates, even minor revisions. Considering `EOS 4.15.2F` has been out for a few months now that seems a little odd.

I'm happy to provide other information to diagnose if needed.

**Comment by tsuna** [comment]
Hi Luke,
These things happen easily due to binary incompatibilities between EOS versions.  You absolutely need to use the correct version of the `EosSdk` RPM that matches your EOS version, otherwise lots of funny things can happen, a segfault being the "nicest" kind of undesirable side effect.

**Comment by innoying** [comment]
That's what I figured, however I'm only seeing `EosSdk-1.7.0-4.15.2F.i686.rpm` as the latest version in the software portal unless I'm missing something

**Comment by tsuna** [comment]
This is probably an oversight, we probably forgot to post the RPMs along with these last two releases.  Let me bring this to the attention of the release team.  If you want, shoot me an email to tsuna-at-arista-dot-com and I'll send you the RPMs you want.

**Comment by innoying** [comment]
Awesome, thanks!

**Comment by tsuna** [comment]
In case anybody finds this issue via a Google search, another symptom than a segfault is an error along the lines of:
```
YourAgent: symbol lookup error: /usr/lib/libeos.so.1: undefined symbol: <C++ mangled symbol name here>
```
