### ISSUE TITLE
[Documentation]privilege configuration 

### ISSUE THREAD

**Issue by takahiro-impara** [aristanetworks/EosSdk#14]
Software image version: 4.15.5M
EOS SDK RPM version:1.8.0/3058241.gamiltoneos

Hi, when I send EOS SDK RPM file into vEOS by scp command it didn't work well.
For solving this problem, it's needed to add privilege configuration as below.

```
testsdk(config)#aaa authorization exec default local 
testsdk(config)#username XXX privilege 15 secret XXX
```

Could you add this direction at [Quickstart page](https://github.com/aristanetworks/EosSdk/wiki/Quickstart%3A-Hello-World)?

Thanks!

**Comment by rmadsen** [comment]
Hi @takahiro-impara - I've updated the [Installation page](https://github.com/aristanetworks/EosSdk/wiki/Downloading-and-Installing-the-SDK#installation-instructions) with a note & pointer to this issue. Thanks for raising this issue!
