### ISSUE TITLE
[Question] Exclusive LLDP Traffic

### ISSUE THREAD

**Issue by CDMarX** [aristanetworks/EosSdk#21]
Greetings!
I'm studying and testing the different interface settings in vEOS and I'm wondering if there is a way to avoid traffic through the interfaces, leaving only lldp working, before any other service starts.

**Comment by tsuna** [comment]
I guess you could do this with an ACL that drops everything except LLDP packets?

**Comment by CDMarX** [comment]
Looks like I was in a completely wrong way! Looking for ACL I found this:
https://eos.arista.com/restricting-access-to-the-switch/
I think it should work!
Thank you Sigoure, by the directions!
