### ISSUE TITLE
Inter-Switch Communication

### ISSUE THREAD

**Issue by alexfrt** [aristanetworks/EosSdk#22]
Hello,

Is there a recommended way of enabling communication between agents running on different EOS instances (in a different network switch, to be more precise)?

Does EOS provides a protocol/API for that or should I implement on my own?

Thanks.

**Comment by tsuna** [comment]
Hi,
We do not provide any kind of specific facility for cross-switch communication, but you can easily leverage any of the many existing open-source projects such as [gRPC](http://www.grpc.io/) or [Thrift](https://thrift.apache.org/).

We provide an example on how to interact with an EOS SDK agent running Thrift here: [models](https://github.com/aristanetworks/EosSdk/blob/master/examples/EosThrift.thrift), [server](https://github.com/aristanetworks/EosSdk/blob/master/examples/ThriftServer.cpp) (that you embed in your agent), [client](https://github.com/aristanetworks/EosSdk/blob/master/examples/ThriftClient.cpp).  You can do something similar with gRPC, which is the new hotness everybody wants to use these days :)

Hope this helps.
