### ISSUE TITLE
Switch unique identifier

### ISSUE THREAD

**Issue by alexfrt** [aristanetworks/EosSdk#23]
Hi,

Is it possible to programatically retrieve some unique identifier for an Arista switch? 

I have read some ZTP docs (https://www.arista.com/assets/data/pdf/TechBulletins/Tech_bulletin_ZTP.pdf) and one of the tenets that is described is the presence of an unique identifier on each Arista switch. 

I wonder that this identifier is used on ZTP as the DHCP client uid, correct? So, how can I programatically retrieve this information from within the switch? Is there a special file or API that exposes this info?

Thank you!

**Comment by rmadsen** [comment]
Hi @alexfrt - we typically use the [System MAC](https://github.com/aristanetworks/EosSdk/blob/master/eos/system.h#L74) address as a unique identifier, though for some features we use the [serial number](https://github.com/aristanetworks/EosSdk/blob/master/eos/system.h#L66). Both are available through SDK APIs, as well as via eAPI (in case you'd rather retrieve this information over an HTTP connection).

After talking with one of the ZTP devs, it sounds like we expose System MAC, Serial Number, Model name, and other fields (at least over HTTP). Let me know if I can provide any other information!

**Comment by alexfrt** [comment]
Thank you @rmadsen, it was very helpful. 

Could you please describe in which situations you use the serial number instead of the System MAC?

Furthermore, how are these info generated, considering EOS on an actual switch, vEOS and cEOS?

**Comment by rmadsen** [comment]
Alright, I got a little more clarification. System MAC is used as the unique identifier for ZTP (though the other fields like `serial number` may be available for use via headers). On EOS the System MAC is generated at the time manufacture, while on vEOS and cEOS it inherits the MAC address from the system it is running on (e.g. the virtual interface of the VM). If you have any more questions about what values are used and where they are used, I'd recommend reaching out to the great folks at support@arista.com. If you have any questions on the SDK front, feel free to re-open this issue.

**Comment by alexfrt** [comment]
Thank you @rmadsen
