### ISSUE TITLE
EOS SDK license 

### ISSUE THREAD

**Issue by krzysztof-sprzaczkowski** [aristanetworks/EosSdk#26]
Hi,
I would like to know under what license Arista provides EOS SDK. Could you provide the contents of the that license? Is it possible to distribute an open reference source code under that license? - assuming that the software calls EOS SDK API. 

I have found some information about Arista's licenses under https://www.arista.com/en/support/product-documentation/eos-feature-licensing - but if I understand correctly they refer rather to EOS running on the switches/platforms and available/enabled features. I haven't found anything about EOS SDK there.
 
Regards,
Krzysztof

**Comment by rmadsen** [comment]
Hi Krzysztof, the [LICENSE](https://github.com/aristanetworks/EosSdk/blob/master/LICENSE) file is where you'll want to look. Let me know if you have any other questions.

**Comment by krzysztof-sprzaczkowski** [comment]
Hi,
Thanks for pointing the LICENSE file out. However I would like know this is the only LICENSE file referring to EOS SDK - or maybe this license applies to EOS SDK stub files available on github repo only. I have to be sure I can base on that LICENSE file as EOS SDK's license. Please confirm that.

If so, beside that I still have a concern regarding usage of the EOS SDK and distribution of a software based on the SDK. I have to know if distributing a open reference source code which uses EOS SDK API does not violate any Arista's license.  

Regards,
Krzysztof

**Comment by tsuna** [comment]
Hi Krzysztof,
As the `LICENSE` indicates, EOS SDK stubs are distributed under a 3-clause BSD license, so the code you write and that uses EOS SDK can be licensed however you want (open source or commercial).  We chose 3-clause BSD specifically to not place any restrictions on the code users write (beyond the small restrictions listed in the 3-clause BSD license, obviously).

When you compile your code against the EOS SDK stubs, you link against a stub version of `libeos.so`, and at runtime the "real" version of `libeos.so` is used instead.  The real version of `libeos.so` is a component of EOS and is subject to the [EOS EULA](https://www.arista.com/assets/data/pdf/software-agreement/EndUserLicenseAgreement.pdf).  But the EOS EULA does not apply to your code.  Your code remains your intellectual property and can be licensed however you want.

Disclaimer: I'm a software engineer, not a lawyer, this reply does not constitute legal advice.  If you still have doubts please ping me at tsuna at arista dot com and I can try to hook you up with one of our lawyers.

**Comment by krzysztof-sprzaczkowski** [comment]
Thanks for your response. 
Regards, Krzysztof
