### ISSUE TITLE
Interface type

### ISSUE THREAD

**Issue by victorhugorodrigues** [aristanetworks/EosSdk#27]
Hi,

On SDK there is different interface types:  INTF_TYPE_ETH, INTF_TYPE_VLAN, INTF_TYPE_LAG, etc...
When a LAG or VLAN is created on one of the production interfaces, the interface type is changed from INTF_TYPE_ETH to represent the new type? Or a new interface to represent the LAG or VLAN is created with its own type?

**Comment by rmadsen** [comment]
A new interface that represents the LAG intf (e.g. `Port-Channel20`) or VLAN interface (e.g. `Vlan3`) will be created with its own type. LAG interfaces can be used with the `intf`, `eth_intf` and `eth_lag_intf` modules.

**Comment by alexfrt** [comment]
If the a new interface is created, then what happens to the "old" interface record that represents a physical interface? It remains being listed by the SDK methods as INTF_TYPE_ETH?

**Comment by rmadsen** [comment]
Yep, they are conceptually different interfaces: both exist simultaneously on the switch.

**Comment by victorhugorodrigues** [comment]
Thanks!
