### ISSUE TITLE
1.10 SDK vs. 1.12

### ISSUE THREAD

**Issue by hubertsokolowskintl** [aristanetworks/EosSdk#32]
Hi,

The version of SDK here on github is 1.10 as this file shows:
https://github.com/aristanetworks/EosSdk/blob/master/version.m4

On the software download page https://www.arista.com/en/support/software-download there is already 1.12 SDK available. 
Is there a reason the github version is older? 
In my project I am downloading SDK stubs from the internet during the build process so I would like to download from github or from ftp site.
Would you be able to provide 1.12 version on FTP site (like you did for 1.9.0) or update the github code to 1.12?

Kind regards,
Hubert

**Comment by ruferp** [comment]
The 1.12.0 stubs (source code) are actually available at https://github.com/aristanetworks/EosSdk/releases (under "Downloads" click on "source code"). 
The 1.12.0 RPMs (binaries) are available on the Software Download page (also linked from the releases page, but you need a login -- there are probably some legal reasons for that, like acknowledging an EULA or such sort of thing). 
Note that the 1.12.0 RPMs for EosSdk are already included in the 4.18.3 EOS image itself (EOS.swi), you only need to overwrite the "native" RPMs if we release EosSdk specific fixes outside of an EOS maintenance release (which was your case, but 4.18.4 will have that fix natively included).
