### ISSUE TITLE
Compiling SDK 1.12.3 outputs 1.10 version information (Makefile)

### ISSUE THREAD

**Issue by jpsenior** [aristanetworks/EosSdk#33]
Steps to reproduce:

1) wget https://github.com/aristanetworks/EosSdk/archive/v1.12.3.tar.gz
2) Extract
3) cd EosSdk-1.12.3
4) ./build.sh
5) ..compile..
6) result binaries, configuration, etc point to version v1.10 -- not v1.12 and are not actually compatible with v1.12 RPMs from arista.com website.

Example:

```
[jp@centos eos-sdk]$ cd EosSdk-1.12.3/
[jp@centos EosSdk-1.12.3]$ grep VERSION *
<snip>
version.m4:m4_define([_VERSION_],[1.10.0])
```

Presuming version.m4 should specify 1.12.3 -- not 1.10.0.

**Comment by hubertsokolowskintl** [comment]
They just replaced the file. They fixed this issue while keeping the same file name for the archive tarball. That's quite unusual but at least it has been fixed.

**Comment by avi-kumar** [comment]
This file is auto-generated in our build, and wasn't done so properly prior to uploading this release to GitHub. We elected to just modify the file in a new commit, and retag this latest commit as release `v1.12.3`.
Sorry for any confusion, but as this file should match the release version, we felt that simply modifying the file would be sufficient.

**Comment by ruferp** [comment]
We had to replace the tarball and keep the version number, because EOS 4.18.4 had already shipped with that version (in a way, github and EosSdk is less important than arista.com and EOS).
