### ISSUE TITLE
Congestion-control mechanisms thru SDK API

### ISSUE THREAD

**Issue by krzysztof-sprzaczkowski** [aristanetworks/EosSdk#40]
Hi,
We need to enable some congestion-control mechanisms for lossless traffic thru SDK API. Especially, we need to have the possibility to configure the following features:

- Priority-Based Flow Control (PFC)
- Enhanced Transmission Selection (ETS)
- Explicit Congestion Notification (ECN)
- Equal-Cost Multi-Path Routing (ECMP)

Are they configurable thru SDK API? 

Regards,
Krzysztof

**Comment by daltonb-arista** [comment]
For a solution available now, eAPI allows you to configure these settings by sending http POST requests containing JSON to the switch's CLI. The documentation for eAPI can be found on-box after enabling eAPI as well as at: https://eos.arista.com/arista-eapi-101/.

We are currently working on an eAPI module for EosSdk which will make it easier to use eAPI via the SDK.

**Comment by ruferp** [comment]
I guess we support the last one (ecmp) by simply adding multiple vias to a route.
For the 3 first ones, like Dalton already mentioned, there is the possibility of using eApi (http/json POST), and a C API for it should be available in an upcoming release (post 4.20). Of course, as far as gets are concerned, you still would have to parse json, and no notifications.
If your business needs cannot be satisfied with the eApi "workaround", maybe it would be best to contact the business side of Arista.
Note that if you use python, eApi is not cumbersome, and you don't even need to go through http, instead you can cut straight through to the Cli via unix domain sockets (which is what EapiClientLib below does), as this example shows:
```
[admin@ol422 ~]$ cat /tmp/a
#!/usr/bin/env python

import EapiClientLib

cmds = "enable , configure , alias one uno , alias two due , show aliases"
cmds = [ c.strip() for c in cmds.split(" , ") ]
eapiClient = EapiClientLib.EapiClient( sysname="ar", disableAaa=True, privLevel=15 )
try:
  response = eapiClient.runCmds( version=1, format="json", cmds=cmds )
  result = response["result"]
  resultStr = "\n".join( str(r) for r in result)
except Exception as e:
  resultStr = str(e)
print resultStr

[admin@ol422 ~]$ python /tmp/a
{}
{}
{}
{}
{'dynamicAliases': {}, 'commandsPath': '', 'aliases': {'two': {'commands': {'10': 'due'}}, 'one': {'commands': {'10': 'uno'}}}}
[admin@ol422 ~]$
```
(

**Comment by krzysztof-sprzaczkowski** [comment]
Thanks for the clarification. 

It looks that in the first step we need to have the ability to configure PFC/ETS - it is priority number 1 now. Because sometimes ago we decided to use SDK API (based on the recommendations provided in the official Arista's documentations), we would like to continue this direction using C/C++ API. In other case, we would have to change the architecture of our SW - that would be an extra effort for us. 

So, could you provide us an approximate date of 4.20 release with C API? -  such information now would very helpful for us.

BTW - 
What is the long term recommendation/strategy for SDK API? Is it going to be obsolete in the future? - or maybe you have a plan to continue to develop and add the missing functionalities to the existing SDK API? Does eAPi is rather preferred API for the EOS-based switches?

Regards,
Krzysztof

**Comment by tsuna** [comment]
EOS SDK isn't going to be obsolete any time soon, it's just that some things may not be accessible through it so as a stop-gap we want to make it easier to access them via eAPI.

EOS SDK and eAPI have very different design goals.  The SDK is here for on-box programming, where you can react to state changing very quickly and have a direct access to the config and status of the device.  eAPI is more for automation/scripts, and doesn't support reacting to state changes (there is no notification mechanism).

**Comment by ruferp** [comment]
Besides the notification mechanism, you definitely want to use the EosSdk for cases with scale, because it is faster.

There are many configuration knobs: having an eapi option allows to hit the configuration gaps in EosSdk as a workaround.
I don't know PFC/ETS: are there any statuses that need to be reacted on?

To get an advanced flavor of the eapi c++ api (note: in EOS 4.20, that header file is internal, it would be a sub-release that makes it public: I think we want to review it some more before casting it into stone).

```
eapi_response_t eapi_mgr::run_config_cmds(const std::vector<std::string> & cmds)

class eapi_response_t {
 public:
   eapi_response_t();
   /** Full constructor. */
   eapi_response_t(bool success, uint32_t error_code,
                   std::string const & error_message,
                   std::vector<std::string> const & responses);
   <... bunch of getters ...>
```
Where the `cmds` are essentially cli command strings. Cli commands do not change from release to release, so that's quite safe.

The show command side is not exposed via an Sdk manager yet (unless you know the internal headers of the less polished inner c api), but might be by the time we cast to stone. Input from the business side can help here, we are just engineers, prioritization is above our pay grade. 

Note that the proposed api is synchronous, and the exposed api has no context (opens a unix-domain socket for each call).
