### ISSUE TITLE
Where to found the MTP doc for Canon ?

### ISSUE THREAD

**Issue by song314** [aristanetworks/EosSdk#41]
EosSdk is a greate open source and helps me a lot. I found the MTP doc for Nikon on Nikon offical website, but I only found the EDSDK on the Canon offical develop website.
	Could you send me the MTP or PTP doc of Canon, or tell me where to get these docs.

	Thanks a lot.

**Comment by avi-kumar** [comment]
Unfortunately, we don't own or maintain MTP or PTP docs for Canon. I can, however, point you to the [Precision Timing Protocol](https://www.arista.com/assets/data/pdf/Whitepapers/Technical_Solution_Guide___Precision_Time_Protocol.pdf) docs for Arista's EOS, although I don't believe this is what you are looking for. Please let us know if there's anything else we can help with.
Thanks!

**Comment by rmadsen** [comment]
To get help with Canon products, try registering as a member at https://www.developersupport.canon.com/ and asking your question there. This GitHub repository is focused on the SDK for [Arista](http://www.arista.com)'s networking devices.
