### ISSUE TITLE
EOS SDK 2.7 stubs for EOS 4.22 ?

### ISSUE THREAD

**Issue by jpsenior** [aristanetworks/EosSdk#47]
Hello there!

Is the release for EOS SDK stubs for 2.7 planned for release soon?  EOS 4.22 specifies the sdk version as 2.7.0, and I need to build agents against the sdk.

They don't seem to be available yet.

**Comment by aparnaka** [comment]
Yes. We will release the 2.7 EOS SDK stubs very soon. In the meantime, if you have an account on Arista's software download page, the stubs are available over there.

**Comment by jpsenior** [comment]
I see that SDK 2.7.0 was on the releases page. 
I built an app against the SDK, and it's again not compiling properly.
It's expecting apps to be linked tb `libeos.so.2.8` -- should be `libeos.so.2.7`

 https://github.com/aristanetworks/EosSdk/blob/master/version.m4 says this is 2.8.0.  **Was this another typo?**  @avi-kumar   It seems version.m4 is again configured for the wrong version.

```
bash-4.3# ldd /usr/bin/MySdkAgent
        linux-gate.so.1 =>  (0xf775a000)
        /usr/lib/libAtimePreload.so (0xf7752000)
        /usr/lib/libLocaltime_r_calls_tzset.so (0xf774f000)
        /usr/lib/libGethostbyname2_calls_resinit.so (0xf774c000)
        /usr/lib/libGetaddrinfo_calls_resinit.so (0xf7749000)
*****************        libeos.so.2.8 => not found *****************
        libstdc++.so.6 => /lib/libstdc++.so.6 (0xf7592000)
        libm.so.6 => /lib/libm.so.6 (0xf754a000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xf752e000)
        libc.so.6 => /lib/libc.so.6 (0xf736c000)
        libdl.so.2 => /lib/libdl.so.2 (0xf7366000)
        /lib/ld-linux.so.2 (0xf775c000)

```

**Comment by avi-kumar** [comment]
Looks like this change should not have made it to EOS 4.22.0F, as it was pushed from a different release. I'll push the proper commits that correspond to EOS 4.22.0F, and update the tarball that has been uploaded to the release page and the Arista SW Download page. Sorry for the confusion!

**Comment by jpsenior** [comment]
Thanks @avi-kumar  for the new release - tested and it works great
