### ISSUE TITLE
EOS SDK Freezes on Import

### ISSUE THREAD

**Issue by ccnPeon** [aristanetworks/EosSdk#48]
whenever I add the rpm for my version and run 'import eossdk', it just hangs.

**Comment by avi-kumar** [comment]
What version of EOS and SDK are you running? The RPM should be installed already with EOS, are you trying to install a different version of the SDK?

**Comment by ccnPeon** [comment]
I tried on a fresh vEOS box and all was good. I realized I didn't need to intstall the rpm.
