### ISSUE TITLE
SDK 2.6.1 release artifacts?

### ISSUE THREAD

**Issue by jpsenior** [aristanetworks/EosSdk#51]
On EOS 4.21.9M, the sdk version is 2.6.1.  We cannot compile our agent without symbols for 2.6.1, and 2.6.0 is not binary backward-compatible for the compiled agent.

Is 2.6.1 coming any time soon?

**Comment by aparnaka** [comment]
The internal difference between the these two specific versions of EosSdk are not invasive and will not cause binary incompatibility. Until we provide 2.6.1, do you mind trying your binary from 2.6.0 running on EOS 4.21.9M? Please let us know if you see any issues there.

**Comment by jpsenior** [comment]
Thanks for your reply.  This may have something to do with how we are instantiating the agent on our side.  I will try to see if I can relax version consistency in our packaging process.
