### ISSUE TITLE
golang examples

### ISSUE THREAD

**Issue by denysaleksandrov** [aristanetworks/EosSdk#52]
Writing agents in Golang is added recently, in 2.11.0.
Could you guys please add some examples of golang agents?

**Comment by gverma9** [comment]
Hi,
Added a new example here:
https://github.com/aristanetworks/EosSdk/blob/master/examples/MacTableIter.go

Thanks!

**Comment by denysaleksandrov** [comment]
Thank you for example. I will try to rewrite my python agents in go.
